server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 262144
    batchwait: 500ms

scrape_configs:
  - job_name: nginx_access
    pipeline_stages:
      - json:
          expressions:
            status: status
            method: method
      - labels:
          status:
          method:
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx_access
          env: prod
          __path__: /var/log/nginx/*clist-prod-access*.json
      - targets: [localhost]
        labels:
          job: nginx_access
          env: dev
          __path__: /var/log/nginx/*clist-dev-access*.json
      - targets: [localhost]
        labels:
          job: nginx_access
          env: legacy
          __path__: /var/log/nginx/*clist-legacy-access*.json

  - job_name: nginx_error
    pipeline_stages:
      - regex:
          expression: '(?P<ts>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)] (?P<pid>\d+#\d+): \*(?P<conn>\d+) (?P<message>.*?), client: (?P<client>[0-9.]+)(, server: (?P<server>[^,]+))?(, request: "(?P<request>[^"]+)")?(, upstream: "(?P<upstream>[^"]+)")?(, host: "(?P<host>[^"]+)")?'
      - timestamp:
          source: ts
          format: 2006/01/02 15:04:05
          action_on_failure: skip
      - labels:
          level:
      - output:
          source: message

    static_configs:
      - targets: [localhost]
        labels:
          job: nginx_error
          env: prod
          __path__: /var/log/nginx/*clist-prod-error*.log
      - targets: [localhost]
        labels:
          job: nginx_error
          env: dev
          __path__: /var/log/nginx/*clist-dev-error*.log
      - targets: [localhost]
        labels:
          job: nginx_error
          env: legacy
          __path__: /var/log/nginx/*clist-legacy-error*.log
