server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 262144
    batchwait: 500ms

scrape_configs:
  - job_name: nginx_access
    relabel_configs:
      - target_label: service
        replacement: nginx
      - target_label: log_type
        replacement: access
    pipeline_stages:
      - json:
          expressions:
            ts: '"@timestamp"'
            host: host
            status: status
            method: request_method
            ip: remote_addr
            uri: uri
            args: args
            protocol: server_protocol
            bytes_sent: bytes_sent
            body_bytes_sent: body_bytes_sent
            request_time: request_time
            upstream_addr: upstream_addr
            upstream_response_time: upstream_response_time
            upstream_status: upstream_status
            user_agent: http_user_agent
            referer: http_referer
            fwd_for: http_x_forwarded_for
      - timestamp:
          source: ts
          format: RFC3339
      - labels:
          host:
          status:
          method:
      - regex:
          source: uri
          expression: '(?P<section>^/[^/]+/)'
      - structured_metadata:
          ip:
          uri:
          args:
          protocol:
          bytes_sent:
          body_bytes_sent:
          request_time:
          upstream_addr:
          upstream_response_time:
          user_agent:
          referer:
          fwd_for:
          section:
    static_configs:
      - targets: [localhost]
        labels:
          env: prod
          __path__: /var/log/nginx/*clist-prod-access*.json
      - targets: [localhost]
        labels:
          env: dev
          __path__: /var/log/nginx/*clist-dev-access*.json
      - targets: [localhost]
        labels:
          env: legacy
          __path__: /var/log/nginx/*clist-legacy-access*.json

  - job_name: nginx_error
    relabel_configs:
      - target_label: service
        replacement: nginx
      - target_label: log_type
        replacement: error
    pipeline_stages:
      - regex:
          expression: '(?P<ts>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)] (?P<pid>\d+#\d+): \*(?P<conn>\d+) (?P<message>.*?), client: (?P<client>[0-9.]+)(, server: (?P<server>[^,]+))?(, request: "(?P<request>[^"]+)")?(, upstream: "(?P<upstream>[^"]+)")?(, host: "(?P<host>[^"]+)")?'
      - timestamp:
          source: ts
          format: "2006/01/02 15:04:05"
          action_on_failure: skip
      - labels:
          level:
          host:
      - structured_metadata:
          pid:
          conn:
          message:
          client:
          server:
          request:
          upstream:
      - output:
          source: message

    static_configs:
      - targets: [localhost]
        labels:
          env: prod
          __path__: /var/log/nginx/*clist-prod-error*.log
      - targets: [localhost]
        labels:
          env: dev
          __path__: /var/log/nginx/*clist-dev-error*.log
      - targets: [localhost]
        labels:
          env: legacy
          __path__: /var/log/nginx/*clist-legacy-error*.log
