
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

common:
  path_prefix: /loki
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1048576

  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2025-05-08
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location:       /loki/index_cache
  filesystem:
    directory:            /loki/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

  ingestion_rate_mb:       30
  ingestion_burst_size_mb: 60

  max_streams_per_user:    5000

  retention_period:        168h

compactor:
  working_directory:     /loki/compactor
  retention_enabled:     true
  retention_delete_delay: 1h
  delete_request_store:  filesystem
